[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200

# Allow scripts to read/write to the script/network directory
fs_permissions = [{ access = "read-write", path = "./script/network/" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

